name: ci

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: test

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install ansible-core
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core

      - name: Restore deps
        uses: actions/cache/restore@v3
        id: cache_ansible_collections
        with:
          path: ansible_collections/
          key: cache_ansible_collections_${{ hashFiles('test/galaxy.yml') }}

      - if: ${{ steps.cache_ansible_collections.outputs.cache-hit != 'true' }}
        name: Install deps
        run: |
          ansible-galaxy collection install -p . -r test/requirements.yml

      - if: ${{ steps.cache_ansible_collections.outputs.cache-hit != 'true' }}
        name: Cache deps
        uses: actions/cache/save@v3
        with:
          path: ansible_collections/
          key: cache_ansible_collections_${{ hashFiles('test/galaxy.yml') }}

      - name: Move repo
        run: |
          mkdir -p ansible_collections/sivel
          mv test ansible_collections/sivel

      - name: Debug test env
        run: |
          ansible-test env
        working-directory: ./ansible_collections/sivel/test

      - name: Run integration tests
        run: |
          ansible-test integration --docker fedora36 -v
        working-directory: ./ansible_collections/sivel/test
